openapi: 3.0.1
info:
  title: EP_Payment_Service
  description: API Definition of EP_Payment_Service
  version: 1.0.0
servers:
- url: http://localhost:8290/billPayment
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
