openapi: 3.0.1
info:
  title: MPesa_TechM_EBPayment_Integration
  description: API Definition of MPesa_TechM_EBPayment_Integration
  version: 1.0.0
servers:
- url: http://localhost:8290/ebPayment
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
